"""
Convert custom HPO .pkl results to the DeepCAVE native format.
WARNING! This script was generated by an AI!

Key difference from previous version:
  configspace.json is taken directly from YAHPO Gym (via BenchmarkSet),
  NOT inferred from observed values. This is critical for benchmarks like
  nb301 which have conditional hyperparameters — inferring from data loses
  all conditions and causes ActiveHyperparameterNotSetError in DeepCAVE.

Supports DeepCAVE v1.3  (8-field Trial, no cpu_time)
     and DeepCAVE v1.4+ (9-field Trial, with cpu_time).

Trial array layout:
  v1.3  → [config_id, budget, seed, costs, start_time, end_time, status, additional]
  v1.4+ → [config_id, budget, seed, costs, cpu_time, start_time, end_time, status, additional]

DeepCAVE minimises costs → we store -accuracy with optimize="lower".
Pass --no-negate to store raw accuracy with optimize="upper".
"""

import json
import os
import pickle
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

STATUS_SUCCESS = 1

KNOWN_SCENARIOS = [
    "rbv2_xgboost", "rbv2_svm", "rbv2_glmnet", "rbv2_ranger",
    "nb301", "lcbench",
]
KNOWN_OPTIMIZERS = [
    "BOHB_Round", "BOHB_Bracket",
    "RandomSearch", "BayesianOptimisation", "GridSearch",
    "SuccessiveHalving", "Hyperband",
]

# Maps scenario → (instance, fidelity_param)
# Needed to initialise BenchmarkSet and drop fidelity from ConfigSpace
SCENARIO_META = {
    "nb301":        {"fidelity": "epoch"},
    "rbv2_xgboost": {"fidelity": "trainsize"},
    "rbv2_svm":     {"fidelity": "trainsize"},
    "rbv2_glmnet":  {"fidelity": "trainsize"},
    "rbv2_ranger":  {"fidelity": "trainsize"},
    "lcbench":      {"fidelity": "epoch"},
}


# ---------------------------------------------------------------------------
# YAHPO ConfigSpace loader
# ---------------------------------------------------------------------------

def _serialize_hp(hp) -> Dict:
    """
    Manually serialize a single hyperparameter to the ConfigSpace JSON format
    (format_version 0.4) that DeepCAVE / ConfigSpace 1.x can read back.
    Works with ConfigSpace 0.6.x which has no built-in JSON writer.
    """
    from ConfigSpace.hyperparameters import (
        UniformFloatHyperparameter,
        UniformIntegerHyperparameter,
        CategoricalHyperparameter,
        OrdinalHyperparameter,
        Constant,
        NormalFloatHyperparameter,
        NormalIntegerHyperparameter,
    )

    if isinstance(hp, UniformFloatHyperparameter):
        return {
            "type": "uniform_float",
            "name": hp.name,
            "lower": float(hp.lower),
            "upper": float(hp.upper),
            "default_value": float(hp.default_value),
            "log": bool(hp.log),
            "meta": None,
        }
    elif isinstance(hp, UniformIntegerHyperparameter):
        return {
            "type": "uniform_int",
            "name": hp.name,
            "lower": int(hp.lower),
            "upper": int(hp.upper),
            "default_value": int(hp.default_value),
            "log": bool(hp.log),
            "meta": None,
        }
    elif isinstance(hp, CategoricalHyperparameter):
        choices = [str(c) for c in hp.choices]
        default = str(hp.default_value)
        if default not in choices:
            default = choices[0]
        return {
            "type": "categorical",
            "name": hp.name,
            "choices": choices,
            "weights": None,
            "default_value": default,
            "meta": None,
        }
    elif isinstance(hp, OrdinalHyperparameter):
        seq = [str(s) for s in hp.sequence]
        return {
            "type": "ordinal",
            "name": hp.name,
            "sequence": seq,
            "default_value": str(hp.default_value),
            "meta": None,
        }
    elif isinstance(hp, Constant):
        return {
            "type": "constant",
            "name": hp.name,
            "value": hp.value,
            "meta": None,
        }
    elif isinstance(hp, NormalFloatHyperparameter):
        return {
            "type": "normal_float",
            "name": hp.name,
            "mu": float(hp.mu),
            "sigma": float(hp.sigma),
            "default_value": float(hp.default_value),
            "log": bool(hp.log),
            "lower": float(hp.lower) if hp.lower is not None else None,
            "upper": float(hp.upper) if hp.upper is not None else None,
            "meta": None,
        }
    elif isinstance(hp, NormalIntegerHyperparameter):
        return {
            "type": "normal_int",
            "name": hp.name,
            "mu": float(hp.mu),
            "sigma": float(hp.sigma),
            "default_value": int(hp.default_value),
            "log": bool(hp.log),
            "lower": int(hp.lower) if hp.lower is not None else None,
            "upper": int(hp.upper) if hp.upper is not None else None,
            "meta": None,
        }
    else:
        raise ValueError(f"Unsupported hyperparameter type: {type(hp)}")


def _serialize_condition(cond) -> Dict:
    """Serialize a condition to ConfigSpace JSON format 0.4."""
    from ConfigSpace.conditions import (
        EqualsCondition, NotEqualsCondition,
        LessThanCondition, GreaterThanCondition,
        InCondition, AndConjunction, OrConjunction,
    )

    if isinstance(cond, AndConjunction):
        return {
            "type": "AND",
            "child": cond.child.name,
            "conditions": [_serialize_condition(c) for c in cond.components],
        }
    elif isinstance(cond, OrConjunction):
        return {
            "type": "OR",
            "child": cond.child.name,
            "conditions": [_serialize_condition(c) for c in cond.components],
        }
    elif isinstance(cond, EqualsCondition):
        return {
            "type": "EQ",
            "child": cond.child.name,
            "parent": cond.parent.name,
            "value": str(cond.value) if isinstance(cond.value, str) else cond.value,
        }
    elif isinstance(cond, NotEqualsCondition):
        return {
            "type": "NEQ",
            "child": cond.child.name,
            "parent": cond.parent.name,
            "value": str(cond.value) if isinstance(cond.value, str) else cond.value,
        }
    elif isinstance(cond, LessThanCondition):
        return {
            "type": "LT",
            "child": cond.child.name,
            "parent": cond.parent.name,
            "value": cond.value,
        }
    elif isinstance(cond, GreaterThanCondition):
        return {
            "type": "GT",
            "child": cond.child.name,
            "parent": cond.parent.name,
            "value": cond.value,
        }
    elif isinstance(cond, InCondition):
        return {
            "type": "IN",
            "child": cond.child.name,
            "parent": cond.parent.name,
            "values": list(cond.values),
        }
    else:
        raise ValueError(f"Unsupported condition type: {type(cond)}")


def cs_to_json_dict(cs) -> Dict:
    """
    Convert a ConfigSpace 0.6.x ConfigurationSpace object to a JSON-compatible
    dict in format_version 0.4 (readable by ConfigSpace 1.x and DeepCAVE 1.4.1).
    """
    hyperparameters = [_serialize_hp(hp) for hp in cs.get_hyperparameters()]
    conditions = [_serialize_condition(c) for c in cs.get_conditions()]
    # Forbiddens — skip for now (not used in YAHPO benchmarks)
    return {
        "name": cs.name if hasattr(cs, "name") else None,
        "hyperparameters": hyperparameters,
        "conditions": conditions,
        "forbiddens": [],
        "python_module_version": "1.2.0",
        "format_version": 0.4,
    }


def get_yahpo_configspace_json(scenario: str, instance: str, yahpo_data_path: str) -> Dict:
    """
    Load the ConfigSpace for a YAHPO Gym benchmark and return it as a dict
    ready to be written to configspace.json.

    Uses drop_fidelity_params=True so the fidelity HP (epoch / trainsize)
    is excluded — matching what was optimised.

    Compatible with ConfigSpace 0.6.x (manual serialization) and 1.x+ (to_json).
    """
    from yahpo_gym import BenchmarkSet, local_config

    local_config.init_config()
    local_config.set_data_path("/Users/ssg/.yahpo_data")

    bench = BenchmarkSet(scenario)
    bench.set_instance(instance)
    cs = bench.get_opt_space(drop_fidelity_params=True)

    # ConfigSpace 1.x+
    if hasattr(cs, "to_json"):
        with tempfile.NamedTemporaryFile(suffix=".json", mode="w", delete=False) as f:
            tmp_path = f.name
        try:
            cs.to_json(tmp_path)
            with open(tmp_path) as f:
                return json.load(f)
        finally:
            os.unlink(tmp_path)

    # ConfigSpace 0.6.x — manual serialization
    return cs_to_json_dict(cs)


# ---------------------------------------------------------------------------
# Config normalisation
# ---------------------------------------------------------------------------

def _normalise_value(val):
    """Convert numpy scalars to plain Python types."""
    if isinstance(val, (bool, np.bool_)):
        return str(val)
    if isinstance(val, np.integer):
        return int(val)
    if isinstance(val, np.floating):
        return float(val)
    return val


def _config_dict(config: Dict) -> Dict:
    return {k: _normalise_value(v) for k, v in config.items()}


def _config_key(cfg: Dict) -> str:
    return json.dumps(cfg, sort_keys=True)


# ---------------------------------------------------------------------------
# Align config values to ConfigSpace types
# ---------------------------------------------------------------------------

def _align_config_to_cs(config: Dict, cs_json: Dict) -> Dict:
    """
    Cast each config value to the type declared in the ConfigSpace JSON.
    This prevents type mismatches when DeepCAVE reconstructs Configuration objects.

    - uniform_float  → float
    - uniform_int    → int
    - categorical    → str  (ConfigSpace stores categorical values as strings)
    """
    hp_types = {}
    for hp in cs_json.get("hyperparameters", []):
        hp_types[hp["name"]] = hp["type"]

    aligned = {}
    for k, v in config.items():
        t = hp_types.get(k)
        if t == "uniform_float":
            aligned[k] = float(v)
        elif t == "uniform_int":
            aligned[k] = int(round(float(v)))
        elif t == "categorical":
            aligned[k] = str(v)
        else:
            # HP not in CS (e.g. fidelity param stored in config by mistake) — skip
            aligned[k] = _normalise_value(v)
    return aligned


# ---------------------------------------------------------------------------
# Main converter
# ---------------------------------------------------------------------------

def convert_run(
    results: List[Dict],
    out_dir: str,
    scenario: str,
    instance: str,
    optimizer: str,
    seed: int,
    cs_json: Dict,
    negate_costs: bool = True,
    deepcave_version: str = "1.3",
) -> None:
    major_minor = tuple(int(x) for x in deepcave_version.split(".")[:2])
    include_cpu_time = major_minor >= (1, 4)

    run_name = f"{optimizer}_{scenario}_{instance}_seed{seed}"
    run_dir = os.path.join(out_dir, run_name)
    os.makedirs(run_dir, exist_ok=True)

    # ------------------------------------------------------------------ 1. configspace.json
    with open(os.path.join(run_dir, "configspace.json"), "w") as f:
        json.dump(cs_json, f, indent=2)

    # ------------------------------------------------------------------ 2. configs.json + origins.json
    # Only keep HPs that are in the ConfigSpace (drop fidelity params, etc.)
    cs_hp_names = {hp["name"] for hp in cs_json.get("hyperparameters", [])}

    configs: Dict[str, Dict] = {}
    origins: Dict[str, None] = {}
    config_to_id: Dict[str, int] = {}

    for r in results:
        raw = _config_dict(r["config"])
        # Keep only HP names present in the ConfigSpace
        filtered = {k: v for k, v in raw.items() if k in cs_hp_names}
        # Align types to CS declarations
        cfg = _align_config_to_cs(filtered, cs_json)
        key = _config_key(cfg)
        if key not in config_to_id:
            cid = len(config_to_id)
            config_to_id[key] = cid
            configs[str(cid)] = cfg
            origins[str(cid)] = None

    with open(os.path.join(run_dir, "configs.json"), "w") as f:
        json.dump(configs, f, indent=2)
    with open(os.path.join(run_dir, "origins.json"), "w") as f:
        json.dump(origins, f, indent=2)

    # ------------------------------------------------------------------ 3. history.jsonl
    budgets_seen: List[float] = []
    costs_seen: List[float] = []
    history_lines: List[str] = []

    for i, r in enumerate(results):
        raw = _config_dict(r["config"])
        filtered = {k: v for k, v in raw.items() if k in cs_hp_names}
        cfg = _align_config_to_cs(filtered, cs_json)
        config_id = config_to_id[_config_key(cfg)]

        budget = float(r["eval_budget"])
        cost = -float(r["result"]) if negate_costs else float(r["result"])

        costs_seen.append(cost)
        if budget not in budgets_seen:
            budgets_seen.append(budget)

        if include_cpu_time:
            trial = [config_id, budget, int(seed), [cost], 0.0,
                     float(i), float(i + 1), STATUS_SUCCESS, {}]
        else:
            trial = [config_id, budget, int(seed), [cost],
                     float(i), float(i + 1), STATUS_SUCCESS, {}]

        history_lines.append(json.dumps(trial))

    with open(os.path.join(run_dir, "history.jsonl"), "w") as f:
        f.write("\n".join(history_lines) + "\n")

    # ------------------------------------------------------------------ 4. meta.json
    budgets_seen.sort()
    objective = {
        "name": "1 - accuracy" if negate_costs else "accuracy",
        "lower": float(min(costs_seen)) if costs_seen else 0.0,
        "upper": float(max(costs_seen)) if costs_seen else 1.0,
        "lock_lower": False,
        "lock_upper": False,
        "optimize": "lower" if negate_costs else "upper",
    }
    meta = {
        "objectives": [objective],
        "budgets": budgets_seen,
        "seeds": [int(seed)],
    }
    with open(os.path.join(run_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)


# ---------------------------------------------------------------------------
# Filename parser
# ---------------------------------------------------------------------------

def parse_pkl_filename(filename: str) -> Tuple[str, str, str, int]:
    stem = filename.replace(".pkl", "")
    parts = stem.split("_")

    seed_token = parts[-1]
    if not seed_token.startswith("seed"):
        raise ValueError(f"Last token '{seed_token}' is not 'seed<N>'")
    seed = int(seed_token[4:])
    remaining = "_".join(parts[:-1])

    optimizer = None
    for opt in sorted(KNOWN_OPTIMIZERS, key=len, reverse=True):
        if remaining.startswith(opt + "_"):
            optimizer = opt
            remaining = remaining[len(opt) + 1:]
            break
    if optimizer is None:
        raise ValueError(f"Cannot identify optimizer in '{filename}'")

    scenario = None
    for sc in sorted(KNOWN_SCENARIOS, key=len, reverse=True):
        if remaining.startswith(sc + "_"):
            scenario = sc
            remaining = remaining[len(sc) + 1:]
            break
    if scenario is None:
        raise ValueError(f"Cannot identify scenario in '{filename}' (after optimizer='{optimizer}')")

    return optimizer, scenario, remaining, seed  # remaining = instance


# ---------------------------------------------------------------------------
# Batch conversion
# ---------------------------------------------------------------------------

def load_pkl(path: str) -> List[Dict]:
    with open(path, "rb") as f:
        return pickle.load(f)


def convert_all(
    in_dir: str,
    out_dir: str,
    yahpo_data_path: str,
    negate_costs: bool = True,
    deepcave_version: str = "1.3",
) -> None:
    os.makedirs(out_dir, exist_ok=True)

    # Cache ConfigSpaces so we don't reload YAHPO for every seed
    cs_cache: Dict[Tuple[str, str], Dict] = {}
    errors = []

    for root, _, files in os.walk(in_dir):
        for fname in sorted(files):
            if not fname.endswith(".pkl"):
                continue

            path = os.path.join(root, fname)
            try:
                optimizer, scenario, instance, seed = parse_pkl_filename(fname)
            except ValueError as e:
                print(f"  [SKIP] {fname}: {e}")
                errors.append((fname, str(e)))
                continue

            # Load ConfigSpace from YAHPO (cached)
            cs_key = (scenario, instance)
            if cs_key not in cs_cache:
                try:
                    print(f"  Loading ConfigSpace for {scenario}/{instance} from YAHPO...", end="", flush=True)
                    cs_cache[cs_key] = get_yahpo_configspace_json(scenario, instance, yahpo_data_path)
                    print(" OK")
                except Exception as e:
                    print(f" FAILED: {e}")
                    errors.append((fname, f"ConfigSpace load failed: {e}"))
                    continue

            try:
                results = load_pkl(path)
                convert_run(
                    results, out_dir,
                    scenario, instance, optimizer, seed,
                    cs_json=cs_cache[cs_key],
                    negate_costs=negate_costs,
                    deepcave_version=deepcave_version,
                )
                run_name = f"{optimizer}_{scenario}_{instance}_seed{seed}"
                print(f"  OK   {fname}  →  {run_name}/")
            except Exception as e:
                import traceback
                print(f"  [ERR] {fname}: {e}")
                traceback.print_exc()
                errors.append((fname, str(e)))

    print(f"\nDone. {len(errors)} error(s).")
    for fname, msg in errors:
        print(f"  • {fname}: {msg}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Convert custom HPO .pkl results to DeepCAVE native format."
    )
    parser.add_argument("--in_dir",  default="../results",
                        help="Directory with .pkl files")
    parser.add_argument("--out_dir", default="../results_deepcave",
                        help="Output directory for DeepCAVE runs")
    parser.add_argument("--yahpo_data", default="./yahpo_data",
                        help="Path to YAHPO Gym data directory (default: ./yahpo_data)")
    parser.add_argument("--deepcave-version", default="1.3",
                        choices=["1.2", "1.3", "1.4", "1.4.1"],
                        help="Installed DeepCAVE version (affects Trial array layout)")
    parser.add_argument("--no-negate", action="store_true",
                        help="Store raw accuracy with optimize='upper' instead of negating")
    args = parser.parse_args()

    convert_all(
        args.in_dir,
        args.out_dir,
        yahpo_data_path=args.yahpo_data,
        negate_costs=not args.no_negate,
        deepcave_version=args.deepcave_version,
    )